/**
 * Helper utility to extract AI generation metadata (Prompt, Negative Prompt, Seed, Sampler, Model, etc.)
 * directly from PNG/JPEG image files generated by Stable Diffusion (A1111, ComfyUI, etc.)
 */

export interface ExtractedMetadata {
  prompt: string;
  negativePrompt: string;
  model: string;
  lora: string;
  seed: string;
  sampler: string;
  cfgScale: number;
  steps: number;
  creator: string;
  tags: string[];
}

// Convert ArrayBuffer to String (UTF-8 safe)
const arrayBufferToString = (buffer: ArrayBuffer): string => {
  try {
    const decoder = new TextDecoder("utf-8");
    return decoder.decode(new Uint8Array(buffer));
  } catch {
    // Fallback to binary string
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return binary;
  }
};

// Search for bytes pattern in Uint8Array
const findBytesPattern = (data: Uint8Array, pattern: number[]): number => {
  const len = pattern.length;
  const limit = data.length - len;
  for (let i = 0; i < limit; i++) {
    let match = true;
    for (let j = 0; j < len; j++) {
      if (data[i + j] !== pattern[j]) {
        match = false;
        break;
      }
    }
    if (match) return i;
  }
  return -1;
};

// Parse A1111 / WebUI Parameters format
export const parseA1111Parameters = (rawText: string): Partial<ExtractedMetadata> => {
  const result: Partial<ExtractedMetadata> = {
    prompt: "",
    negativePrompt: "",
    model: "",
    lora: "",
    seed: "",
    sampler: "",
    cfgScale: 7,
    steps: 20,
    tags: [],
  };

  const text = rawText.trim();
  if (!text) return result;

  // WebUI text format typically:
  // [Positive Prompt]
  // Negative prompt: [Negative Prompt]
  // Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 12345, Size: 512x512, Model hash: xxxx, Model: modelName, Lora hashes: "..."

  // 1. Identify key-value line (usually starts with Steps:)
  const stepsIndex = text.lastIndexOf("Steps:");
  if (stepsIndex === -1) {
    // If no Steps line, just treat the whole text as positive prompt
    result.prompt = text;
    return result;
  }

  const mainPromptPart = text.substring(0, stepsIndex).trim();
  const settingsPart = text.substring(stepsIndex).trim();

  // 2. Parse Positive & Negative Prompt
  const negativePromptIndex = mainPromptPart.indexOf("Negative prompt:");
  if (negativePromptIndex !== -1) {
    result.prompt = mainPromptPart.substring(0, negativePromptIndex).trim();
    result.negativePrompt = mainPromptPart.substring(negativePromptIndex + "Negative prompt:".length).trim();
  } else {
    result.prompt = mainPromptPart;
  }

  // Clean prompt trailing commas or newlines
  if (result.prompt.endsWith(",")) {
    result.prompt = result.prompt.substring(0, result.prompt.length - 1).trim();
  }

  // 3. Parse Settings fields
  const settingsList = settingsPart.split(",").map(s => s.trim());
  const settingsMap: Record<string, string> = {};

  settingsList.forEach(item => {
    const colonIndex = item.indexOf(":");
    if (colonIndex !== -1) {
      const key = item.substring(0, colonIndex).trim();
      const val = item.substring(colonIndex + 1).trim();
      settingsMap[key] = val;
    }
  });

  if (settingsMap["Steps"]) result.steps = parseInt(settingsMap["Steps"], 10) || 20;
  if (settingsMap["Sampler"]) result.sampler = settingsMap["Sampler"];
  if (settingsMap["CFG scale"]) result.cfgScale = parseFloat(settingsMap["CFG scale"]) || 7;
  if (settingsMap["Seed"]) result.seed = settingsMap["Seed"];
  if (settingsMap["Model"]) result.model = settingsMap["Model"];

  // Extract LoRAs from prompt (e.g., <lora:name:weight>)
  const loraRegex = /<lora:([^:]+):[^>]+>/g;
  const loras: string[] = [];
  let match;
  while ((match = loraRegex.exec(result.prompt)) !== null) {
    loras.push(match[1]);
  }
  if (loras.length > 0) {
    result.lora = loras.join(", ");
  } else if (settingsMap["Lora hashes"]) {
    // If WebUI lists Lora hashes, parse keys
    // e.g. "lora_name: hash"
    const loraHashes = settingsMap["Lora hashes"].replace(/["{}]/g, "");
    const parsedLoras = loraHashes.split(",").map(lh => lh.split(":")[0].trim()).filter(Boolean);
    if (parsedLoras.length > 0) {
      result.lora = parsedLoras.join(", ");
    }
  }

  // Auto tags based on Model, Sampler
  const tags: string[] = [];
  if (result.model) tags.push(result.model);
  if (settingsMap["Size"]) tags.push(settingsMap["Size"]);
  result.tags = tags;

  return result;
};

// Parse ComfyUI JSON format
export const parseComfyUIJSON = (jsonStr: string): Partial<ExtractedMetadata> => {
  const result: Partial<ExtractedMetadata> = {
    prompt: "",
    negativePrompt: "",
    model: "",
    lora: "",
    seed: "",
    sampler: "",
    cfgScale: 7,
    steps: 20,
    tags: ["ComfyUI"],
  };

  try {
    const graph = JSON.parse(jsonStr);
    
    // ComfyUI workflow has nodes. We look for classes like KSampler, CLIPTextEncode, LoraLoader, CheckpointLoaderSimple.
    let positiveText = "";
    let negativeText = "";
    const loras: string[] = [];

    Object.keys(graph).forEach(key => {
      const node = graph[key];
      const nodeType = node.class_type;

      if (nodeType === "KSampler" || nodeType === "KSamplerAdvanced") {
        const inputs = node.inputs;
        if (inputs) {
          if (inputs.seed !== undefined) result.seed = String(inputs.seed);
          if (inputs.noise_seed !== undefined) result.seed = String(inputs.noise_seed);
          if (inputs.steps !== undefined) result.steps = parseInt(inputs.steps, 10) || 20;
          if (inputs.cfg !== undefined) result.cfgScale = parseFloat(inputs.cfg) || 7;
          if (inputs.sampler_name !== undefined) result.sampler = String(inputs.sampler_name);
          if (inputs.scheduler !== undefined) {
            result.sampler = `${result.sampler} ${inputs.scheduler}`;
          }
        }
      } 
      else if (nodeType === "CheckpointLoaderSimple" || nodeType === "CheckpointLoader") {
        if (node.inputs && node.inputs.ckpt_name) {
          result.model = String(node.inputs.ckpt_name).replace(/\.[^.]+$/, ""); // strip extension
        }
      } 
      else if (nodeType === "LoraLoader") {
        if (node.inputs && node.inputs.lora_name) {
          const name = String(node.inputs.lora_name).replace(/\.[^.]+$/, "");
          loras.push(name);
        }
      } 
      else if (nodeType === "CLIPTextEncode") {
        // A CLIPTextEncode might be positive or negative.
        // We'll gather CLIPTextEncode node values.
        const text = node.inputs?.text;
        if (text && typeof text === "string" && text.trim()) {
          const trimmed = text.trim();
          // Heuristic: If it has negative-like keywords, or if it is shorter and contains negative terms
          const isNegative = /nsfw|bad|ugly|deformed|mutation|blurry|low quality/i.test(trimmed);
          if (isNegative) {
            if (!negativeText) negativeText = trimmed;
          } else {
            // Take the first or longest non-negative one as positive prompt
            if (!positiveText || trimmed.length > positiveText.length) {
              // But keep old positive if it's already long
              if (!positiveText) {
                positiveText = trimmed;
              } else {
                // Heuristic: combine or take longest
                positiveText = trimmed;
              }
            }
          }
        }
      }
    });

    result.prompt = positiveText;
    result.negativePrompt = negativeText;
    if (loras.length > 0) result.lora = loras.join(", ");
    if (result.model && result.tags) result.tags.push(result.model);

  } catch (err) {
    console.error("Failed to parse ComfyUI JSON metadata:", err);
  }

  return result;
};

// Parse metadata from PNG chunks
const parsePNGMetadata = (arrayBuffer: ArrayBuffer): Partial<ExtractedMetadata> => {
  const view = new DataView(arrayBuffer);
  
  // Verify PNG signature: 89 50 4E 47 0D 0A 1A 0A
  if (
    view.getUint32(0) !== 0x89504e47 ||
    view.getUint32(4) !== 0x0d0a1a0a
  ) {
    return {};
  }

  let offset = 8;
  const length = arrayBuffer.byteLength;
  
  let a1111Params = "";
  let comfyUIPrompt = "";
  let comfyUIWorkflow = "";

  while (offset < length) {
    if (offset + 8 > length) break;
    
    const chunkLength = view.getUint32(offset);
    const chunkType = String.fromCharCode(
      view.getUint8(offset + 4),
      view.getUint8(offset + 5),
      view.getUint8(offset + 6),
      view.getUint8(offset + 7)
    );

    if (chunkType === "IEND") break;

    // We only care about metadata chunks: tEXt, iTXt
    if ((chunkType === "tEXt" || chunkType === "iTXt") && chunkLength > 0) {
      if (offset + 8 + chunkLength > length) break;
      
      const chunkData = new Uint8Array(arrayBuffer, offset + 8, chunkLength);
      
      if (chunkType === "tEXt") {
        // Format: keyword\0text
        const nullIndex = chunkData.indexOf(0);
        if (nullIndex !== -1) {
          const keyword = new TextDecoder("utf-8").decode(chunkData.subarray(0, nullIndex));
          const text = new TextDecoder("utf-8").decode(chunkData.subarray(nullIndex + 1));
          
          if (keyword === "parameters") {
            a1111Params = text;
          } else if (keyword === "prompt") {
            comfyUIPrompt = text;
          } else if (keyword === "workflow") {
            comfyUIWorkflow = text;
          }
        }
      } 
      else if (chunkType === "iTXt") {
        // Format: keyword\0compression_flag\0compression_method\0language_tag\0translated_keyword\0text
        const nullIndex = chunkData.indexOf(0);
        if (nullIndex !== -1) {
          const keyword = new TextDecoder("utf-8").decode(chunkData.subarray(0, nullIndex));
          const compFlag = chunkData[nullIndex + 1];
          const compMethod = chunkData[nullIndex + 2];
          
          // Locate text after remaining null-terminated strings (language_tag and translated_keyword)
          let restIndex = nullIndex + 3;
          // Skip language_tag
          while (restIndex < chunkData.length && chunkData[restIndex] !== 0) restIndex++;
          restIndex++; // skip null
          
          // Skip translated_keyword
          while (restIndex < chunkData.length && chunkData[restIndex] !== 0) restIndex++;
          restIndex++; // skip null

          if (restIndex < chunkData.length) {
            let textBytes = chunkData.subarray(restIndex);
            
            // If text is uncompressed (compFlag === 0)
            if (compFlag === 0) {
              const text = new TextDecoder("utf-8").decode(textBytes);
              if (keyword === "parameters") {
                a1111Params = text;
              } else if (keyword === "prompt") {
                comfyUIPrompt = text;
              } else if (keyword === "workflow") {
                comfyUIWorkflow = text;
              }
            }
            // If compressed (not standard for SD params, but possible)
            // We ignore for simplicity or handle if we had zlib, but standard WebUI uses uncompressed iTXt/tEXt
          }
        }
      }
    }

    offset += 8 + chunkLength + 4; // Length (4) + Type (4) + Data (chunkLength) + CRC (4)
  }

  if (a1111Params) {
    return parseA1111Parameters(a1111Params);
  }
  if (comfyUIPrompt) {
    return parseComfyUIJSON(comfyUIPrompt);
  }

  return {};
};

// Parse JPEG EXIF or XMP (by scanning raw strings inside buffer as fallback)
const parseJPEGMetadata = (arrayBuffer: ArrayBuffer): Partial<ExtractedMetadata> => {
  // Parsing a full EXIF tree in pure custom code is extremely complex.
  // Instead, since Stable Diffusion parameters are saved as plain text inside JPEG APP1 or APP2 chunks, 
  // we can use a highly robust fallback: Convert buffer to string and scan for metadata signatures.
  const rawString = arrayBufferToString(arrayBuffer);
  
  // 1. Look for A1111 format in JPEG (often marked by EXIF or key-value patterns)
  // Stable Diffusion WebUI writes parameters as a "parameters" text block.
  // In JPEG EXIF, it typically starts with "parameters\0" or "parameters:"
  const paramIndex = rawString.indexOf("parameters\0");
  if (paramIndex !== -1) {
    const searchStart = paramIndex + "parameters\0".length;
    // Parameters end with Steps line. Find the next "Steps:" block and capture until end of line
    const stepsIndex = rawString.indexOf("Steps:", searchStart);
    if (stepsIndex !== -1) {
      // Find end of settings line (usually followed by EXIF markers or null)
      let endIndex = stepsIndex + 6;
      while (endIndex < rawString.length) {
        const charCode = rawString.charCodeAt(endIndex);
        // End of parameters block is typically a null byte or special EXIF separator (< 32, except tab/newline)
        if (charCode < 32 && charCode !== 9 && charCode !== 10 && charCode !== 13) {
          break;
        }
        endIndex++;
      }
      const rawParams = rawString.substring(paramIndex + "parameters\0".length, endIndex);
      return parseA1111Parameters(rawParams);
    }
  }

  // 2. Fallback: Search for "Steps: " inside JPEG and parse around it
  const stepsIndex = rawString.indexOf("Steps:");
  if (stepsIndex !== -1) {
    // Walk backwards to find the prompt start
    // Usually, in JPEG, the metadata block starts with positive prompt, and ends with settings.
    // Let's grab some text before "Steps:" (e.g. 5000 characters or to a null byte)
    let startIndex = stepsIndex - 1;
    while (startIndex > 0 && stepsIndex - startIndex < 8000) {
      const charCode = rawString.charCodeAt(startIndex);
      // Stop when we hit EXIF binary marker (null bytes, or characters outside printable range)
      if (charCode < 32 && charCode !== 9 && charCode !== 10 && charCode !== 13) {
        startIndex++;
        break;
      }
      startIndex--;
    }
    
    // Find the end of parameters
    let endIndex = stepsIndex + 6;
    while (endIndex < rawString.length && endIndex - stepsIndex < 1000) {
      const charCode = rawString.charCodeAt(endIndex);
      if (charCode < 32 && charCode !== 9 && charCode !== 10 && charCode !== 13) {
        break;
      }
      endIndex++;
    }

    const candidateText = rawString.substring(startIndex, endIndex);
    if (candidateText.includes("Steps:") && (candidateText.includes("Sampler:") || candidateText.includes("Seed:"))) {
      // Clean up text: sometimes binary garbage remains at the beginning
      // A1111 parameters always have steps, sampler, cfg scale, seed.
      // Let's filter out non-printable ASCII characters from the beginning
      let cleanedText = candidateText;
      const firstPrintable = cleanedText.search(/[a-zA-Z0-9<"']/);
      if (firstPrintable !== -1) {
        cleanedText = cleanedText.substring(firstPrintable);
      }
      return parseA1111Parameters(cleanedText);
    }
  }

  return {};
};

/**
 * Extract metadata directly from a raw image buffer (useful for Server-side environments).
 */
export const parseImageBufferMetadata = (buffer: ArrayBuffer, fileName: string): Partial<ExtractedMetadata> => {
  try {
    const ext = fileName.toLowerCase().split(".").pop() || "";
    if (ext === "png") {
      return parsePNGMetadata(buffer);
    } else if (ext === "jpg" || ext === "jpeg") {
      return parseJPEGMetadata(buffer);
    } else {
      // WEBP or other fallback
      const rawString = arrayBufferToString(buffer);
      if (rawString.includes("Steps:")) {
        const stepsIndex = rawString.indexOf("Steps:");
        const startIndex = Math.max(0, stepsIndex - 4000);
        const endIndex = Math.min(rawString.length, stepsIndex + 1000);
        const candidateText = rawString.substring(startIndex, endIndex);
        return parseA1111Parameters(candidateText);
      }
    }
  } catch (err) {
    console.error("Error in parseImageBufferMetadata:", err);
  }
  return {};
};

/**
 * Main function to extract metadata from an uploaded image File.
 */
export const extractMetadata = async (file: File): Promise<Partial<ExtractedMetadata>> => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      const buffer = e.target?.result as ArrayBuffer;
      if (!buffer) {
        resolve({});
        return;
      }

      try {
        if (file.type === "image/png" || file.name.toLowerCase().endsWith(".png")) {
          resolve(parsePNGMetadata(buffer));
        } else if (
          file.type === "image/jpeg" || 
          file.name.toLowerCase().endsWith(".jpg") || 
          file.name.toLowerCase().endsWith(".jpeg")
        ) {
          resolve(parseJPEGMetadata(buffer));
        } else {
          // WEBP or other
          // Try both fallback strings search
          const rawString = arrayBufferToString(buffer);
          if (rawString.includes("Steps:")) {
            const stepsIndex = rawString.indexOf("Steps:");
            let startIndex = Math.max(0, stepsIndex - 4000);
            let endIndex = Math.min(rawString.length, stepsIndex + 1000);
            const candidateText = rawString.substring(startIndex, endIndex);
            resolve(parseA1111Parameters(candidateText));
          } else {
            resolve({});
          }
        }
      } catch (err) {
        console.error("Error in metadata extraction:", err);
        resolve({});
      }
    };

    reader.onerror = () => {
      resolve({});
    };

    // Read only first 2MB of file to avoid freezing client browser with massive raw images
    const slice = file.slice(0, 2 * 1024 * 1024);
    reader.readAsArrayBuffer(slice);
  });
};
